### ISSUE TITLE
BitBank RateLimit Issue

### ISSUE THREAD

**Issue by CHANist** [bitbankinc/bitbank-api-docs#94] opened 2023-06-29 03:47 UTC
When I call `GET /user/spot/active_orders` API over suggested rate limit, 
instead of receiving 10009, I receive 20001, which seems a wrong error code. 

10009 You sent requests too frequently. Retry later with decreased requests.
20001 Authentication failed api authorization.

Can you confirm this is an issue?

**Comment by CHANist** [comment] 2023-07-05 04:25
any ideas?

**Comment by mojamonja** [comment] 2023-07-10 08:49
@CHANist Thanks for creating this issue and I apologize the late reply. 🙇 

I think that 20001 is caused by wrong nonce. (this is one of common root of cause of 20001.)
If you call API many at once, request order may change (by network latency etc.) and it cause violation of nonce "increased every time."
A solution is create some API-keys and use them concurrently. Nonce limitation is for each API-key, so you can call many at once without nonce violation.
Also note that API rate limit is per-user (and per QUERY/UPDATE), so creating API-keys and using them concurrently does not relax the limit. (you'll get 10009 in this case)

**Comment by MtkN1** [comment] 2023-08-02 05:22
I was facing the same problem.
I will try to deal with it by creating some API-keys.

However, I would like to request an improvement on this "increasing every time" nonce specification.
Asynchronous requests almost always result in a 20001 error.
This puts the responsibility for network latency on the user, and undermines response equality.
This is not the case with the REST APIs of many other exchanges.

**Comment by mojamonja** [comment] 2023-08-02 07:06
@MtkN1 Thank you for your feedback.
We often receive such comments that the nonce requirement is bad for concurrent requests.
We are aware of the issue and we are considering to adopt recvWindow style which like Binance API in the future.
It will take time to be available though. We would appreciate your patience.

**Comment by MtkN1** [comment] 2023-08-02 12:32
Thank you for considering my request! I 💓 bitbank!

**Comment by MtkN1** [comment] 2024-08-23 15:40
I was looking forward to it! 🤗  https://bitbank.cc/blog/articles/406396361

**Comment by mojamonja** [comment] 2024-08-27 06:02
@CHANist @MtkN1
As you (may) have already heard, we recently released a new ACCESS-TIME-WINDOW method, in addition to the existing (ACCESS-NONCE) method.
https://github.com/bitbankinc/bitbank-api-docs/blob/a2ac9a12f438a59830c1b10e7070740554dca6ac/rest-api.md#access-time-window-method

By leveraging this, I think we're now able to request concurrently/asynchronously without being bothered by nonce 20001 errors. (Note that rate limit per user still applies. This is about request authenticating.)
With that in mind, I'll close this issue, but feel free to open a new issue when you feel any problems or improvement request ;)

**Closed by mojamonja** 2024-08-27 06:02 UTC
